### ISSUE TITLE
pingone_application - Use set -vs- list on redirect_uris

### ISSUE THREAD

**Issue by tsigle** [pingidentity/terraform-provider-pingone#148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PingOne Terraform provider Version
- registry.terraform.io/pingidentity/pingone v0.4.0

### Terraform Version
- Terraform v1.2.9 on darwin_arm64

### Affected Resource(s)

- pingone_application

### Terraform Configuration Files
```hcl
resource "pingone_application" "my_awesome_web_app" {
  environment_id = pingone_environment.my_environment.id
  name           = "Terry's Awesome Web App"
  enabled        = true

  oidc_options {
    type                        = "WEB_APP"
    grant_types                 = ["AUTHORIZATION_CODE", "REFRESH_TOKEN"]
    response_types              = ["CODE"]
    token_endpoint_authn_method = "CLIENT_SECRET_BASIC"
    redirect_uris               = ["https://abc", "https://def"]
  }
}
```

### Expected Behavior
Expect the redirect_uris to be updated regardless of order.  I believe it's been identified that we should use a set vs a list.

### Actual Behavior
When the array is not sorted (i.e. ` ["https://def", "https://abc"]`) terraform plan will try to change over and over.

### Steps to Reproduce

1. `terraform apply`
2. make a change of the order
3. `terraform apply`

**Comment by patrickcping** [comment]
Spot on, thanks for raising the issue!

https://github.com/pingidentity/terraform-provider-pingone/blob/c98f5780bfe3326d5244738f62fad790c1517293/internal/service/sso/resource_application.go#L182-L198

`redirect_uris` and `post_logout_redirect_uris` should be `TypeSet` and not `TypeList`, with adjustment to tests

Will fix for the next release (due mid or end of this week)
