### ISSUE TITLE
Support for `pingone_user` Data Source

### ISSUE THREAD

**Issue by terraform-pingidentity-modules** [pingidentity/terraform-provider-pingone#163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Allow for getting a user_id from a pingone_user data source with username as input.

### New or Affected Data Sources(s)

- pingone_user

### Potential Terraform Configuration

```hcl
data "pingone_user" "example_by_username" {
  username = "alice"
}
```

### References

* #0000

**Comment by samir-gandhi** [comment]
use case:
when creating a new environment, it's common to want a higher admin user to have identity_data_admin role over the environment (for SSO and other env maintenance).

that block looks like:
```hcl
data "pingone_role" "identity_data_admin" {
  name = "Identity Data Admin"
  depends_on = [
    pingone_environment.terry_tf_trial
  ]
}

resource "pingone_role_assignment_user" "admin_sso" {
  environment_id       = var.environment_id
  user_id              = var.admin_user_id
  role_id              = data.pingone_role.identity_data_admin.id
  scope_environment_id = resource.pingone_environment.terry_tf_trial.id
}
```

we want to avoid users needing to look up a user id manually and just provide a known username in the admin environment

**Comment by patrickcping** [comment]
Ok this makes sense, I'll look to include it in a suitable milestone release
