### ISSUE TITLE
Support for Organization data source

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-pingone#21]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for organisation data source

### New or Affected Resource(s)

- pingone_organization

### Potential Terraform Configuration

```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
data "pingone_organization" "example_by_name" {
  name = "internal_org_name_example"
}
```

### References

* #0000

**Comment by tsigle** [comment]
When you add this, it would be nice to get the several URLs available based on the region of the organization.

Example: NorthAmerica
  https://console.pingone.com
  https://auth.pingone.com
  https://apps.pingone.com
  https://api.pingone.com

and maybe DaVinci (however I could see that as part of the DaVinci provider):
  https://orchestrate-api.pingone.com

**Comment by patrickcping** [comment]
@tsigle I've added static hostnames to the output of this data source, but as they don't come from the platform via the API (they're hardcoded in the provider code), the values won't dynamically change when #209 is implemented.  Inclusion of these parameters is a temporary workaround until the platform API itself returns the correct hostnames for the client context
