### ISSUE TITLE
Inconsistent case usage between API and Terraform Params

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#313]
There is a mismatch of casing between PingOne API and Terraform Block Attributes. 

The API uses camelCase by default and Terraform requires snake_case. This means we need to convert everything from API (read) to TF (write) to compare the result, e.g.
```
      {
        "id": <uuid>,
        "name": "Test Worker",
        "enabled": true,
        "hiddenFromAppPortal": false,
        "type": "WORKER",
        "accessControl": {
          "role": {
            "type": "ADMIN_USERS_ONLY"
          }
        },
        "protocol": "OPENID_CONNECT",
        "responseTypes": [
          "TOKEN"
        ],
        "grantTypes": [
          "CLIENT_CREDENTIALS",
          "IMPLICIT"
        ],
        "refreshTokenDuration": 2592000,
        "tokenEndpointAuthMethod": "CLIENT_SECRET_POST",
        "pkceEnforcement": "OPTIONAL",
        "refreshTokenRollingDuration": 15552000
      }
```

and in the terraform block the required params are all snake_case, so to compare one must convert each and every key that contains camelCase;
```
    const oidc_options = {
      type,
      grant_types: grantTypes,
      response_types: responseTypes,
      pkce_enforcement: pkceEnforcement,
      token_endpoint_auth_method: tokenEndpointAuthMethod,
    };
```

The casing should be consistent across both

**Comment by patrickcping** [comment]
hi @dbryar !  Thanks for raising.  The casing of the attribute names is per Hashicorp's guidelines in schema design (ref: https://developer.hashicorp.com/terraform/plugin/framework/handling-data/schemas#attributes ), which also means we're consistent with other providers from other vendors.  On this point, we're not planning to change the casing of the attribute names.

It does unfortunately mean there isn't a direct correlation between the API schema and the Terraform schema in some cases.

You may notice that we also, in some cases, change the attribute names altogether (to align to the intended "use case" or the wording in the Admin Console UI), or introduce different blocks to differentiate resource types (such as the `oidc_options` block, which allows us to make use of Terraform's own schema validation utilities to ensure that we catch more invalid attribute combinations at `plan` time and not `apply` time, and avoids building in unnecessary validation code into the provider).  This approach also helps customers who are not familiar with the API schema (which we expect to be the majority of users) to quicker get to grips with creating certain types of resources.

We're collecting feedback on attribute naming and block use as we move towards v1.0.0 of the provider though, so specific points of improvement around attribute names/values and block use is always welcome, mostly likely in their own dedicated GH issues to keep discussion focused.

**Comment by patrickcping** [comment]
As an aside, when converting existing configuration (API based) to Terraform, it's worth exploring the `terraform import ...` feature documented on each of the resources, coupled with `terraform state show ...`.  This method provides a relatively simple way to convert a single instance of resource configuration to HCL.
