### ISSUE TITLE
Inconsistent region param values across PingOne API and Terraform

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#314]
The values for a given param are inconsistent across the two, e.g.
`"region": "AP" // Output from API`

Terraform Docs.
> `region (String)` The region to create the environment in. Should be consistent with the PingOne organisation region. Valid options are `AsiaPacific` `Canada` `Europe` and `NorthAmerica`. Default can be set with the `PINGONE_REGION` environment variable.

**Comment by dbryar** [comment]
I understand the reasoning in #313 but this is a straight up inconsistency as teh value is being stored or processed by Ping as one or the other, not both?

**Comment by samir-gandhi** [comment]
DaVinci properties for P1 connectors typically follow the two letter abbr as well.
