### ISSUE TITLE
Unable to find pre-created resource "OpenID Connect"

### ISSUE THREAD

**Issue by kwri-avongluck** [pingidentity/terraform-provider-pingone#318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version

0.11.1

### Terraform Version
Terraform v1.3.7

### Affected Resource(s)
- pingone_resource

### Terraform Configuration Files
```hcl
data "pingone_resource" "openid" {
  environment_id = pingone_environment.agent_environment.id
  name = "OpenID Connect"
}
```

### Expected Behavior
Leverage the pre-existing openid pongone_resource 

### Actual Behavior

```
Error: Cannot find resource OpenID Connect
with data.pingone_resource.openid
on data.tf line 14, in data "pingone_resource" "openid":
data "pingone_resource" "openid" {
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
<img width="1305" alt="Screenshot 2023-03-27 at 10 46 37 AM" src="https://user-images.githubusercontent.com/40496582/228019728-e86d15a5-7103-43a6-9196-c25d1fb32a7d.png">

**Comment by patrickcping** [comment]
Hi @kwri-avongluck thanks for raising!

To select the default OpenID Connect resource, you use the name `openid`.  This isn't clear in the documentation, so we'll make changes to make this clearer.

E.g.
```
data "pingone_resource" "openid" {
  environment_id = pingone_environment.agent_environment.id
  name = "openid"
}
```

**Comment by kwri-avongluck** [comment]
This indeed resolves the issue for us.  Thanks for confirming!
