### ISSUE TITLE
`token_endpoint_auth_method` in pingone_application has extra `n`

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#320]
│ Error: Unsupported argument
│ 
│   on terraform.tf line 452, in resource "pingone_application" "beem_wallet":
│  452:     token_endpoint_auth_method      = "NONE"
│ 
│ An argument named "token_endpoint_auth_method" is not expected here. Did you mean
│ "token_endpoint_authn_method"?

`authn`, appears to be a typo (extra `n`)

**Comment by dbryar** [comment]
And on the same page, `allow_wildcard_in_redirect_uris` has an extra `s`

│ Error: Unsupported argument
│ 
│   on terraform.tf line 454, in resource "pingone_application" "beem_wallet":
│  454:     allow_wildcard_in_redirect_uris = true
│ 
│ An argument named "allow_wildcard_in_redirect_uris" is not expected here. Did you mean
│ "allow_wildcards_in_redirect_uris"?

both values in the API are without the additional characters

**Comment by tsigle** [comment]
@dbryar Thank you for creating this issue.  There probably won't be a response to this until next week as the resource to review is out of the office.

**Comment by dbryar** [comment]
Point 1 - I understand the distinction so if it is intended then so be it.
Point 2 - I am mapping directly from API Getters using a `camelToSnake` function, so these anomalies in key names are annoying, but trivial to correct. It just adds overhead to map between the two
