### ISSUE TITLE
Gateway configuration at sign on policy action missing

### ISSUE THREAD

**Issue by alekamuniqa** [pingidentity/terraform-provider-pingone#386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently it is possible to define a Gateway via Terraform. However, it is not possible to add that Gateway to a "Login" Sign on action as it is possible via the PingOne console
Example in PingOne console (section "MIGRATE GATEWAY USERS UPON FIRST AUTHENTICATION"):
![image](https://github.com/pingidentity/terraform-provider-pingone/assets/135047369/c49063c8-b4c5-4a27-a485-bf0bf3428a99)

### New or Affected Resource(s)
- pingone_sign_on_policy_action

At the nested schema for "login", an array of pingone_gateway and the corresponding "name" of one user_type should be optionally providable.

### Potential Terraform Configuration

```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
```

**Comment by patrickcping** [comment]
hi @alekamuniqa , thanks for raising!  Agreed, this needs adding to the provider
