### ISSUE TITLE
Cannot allocate OIDC scopes to an application

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version
0.14.0

### Terraform Version
1.4.2

### Affected Resource(s)
- pingone_application
- pingone_application_resource_grant

### Terraform Configuration Files
```hcl
data "pingone_resource" "openid" {
  environment_id = pingone_environment.dev.id
  name           = "openid"
}

data "pingone_resource_scope" "openid_openid" {
  environment_id = pingone_environment.dev.id
  resource_id    = data.pingone_resource.openid.id
  name           = "openid"
}

data "pingone_resource_scope" "openid_profile" {
  environment_id = pingone_environment.dev.id
  resource_id    = data.pingone_resource.openid.id
  name           = "profile"
}

data "pingone_resource_scope" "openid_email" {
  environment_id = pingone_environment.dev.id
  resource_id    = data.pingone_resource.openid.id
  name           = "email"
}

data "pingone_resource_scope" "openid_address" {
  environment_id = pingone_environment.dev.id
  resource_id    = data.pingone_resource.openid.id
  name           = "address"
}

data "pingone_resource_scope" "openid_phone" {
  environment_id = pingone_environment.dev.id
  resource_id    = data.pingone_resource.openid.id
  name           = "phone"
}

resource "pingone_application" "postman" {
  environment_id = pingone_environment.dev.id
  name           = "Postman"
  description    = "Client to access PingOne API using Postman"
  icon {
    id   = pingone_image.postman.id
    href = pingone_image.postman.uploaded_image[0].href
  }
  enabled                = true
  hidden_from_app_portal = false
  oidc_options {
    type = "NATIVE_APP"
    response_types = [
      "CODE",
      "TOKEN"
    ]
    grant_types = [
      "AUTHORIZATION_CODE",
      "IMPLICIT",
      "REFRESH_TOKEN",
      "CLIENT_CREDENTIALS"
    ]
    token_endpoint_authn_method = "CLIENT_SECRET_BASIC"
    pkce_enforcement            = "OPTIONAL"
  }
}

resource "pingone_application_resource_grant" "oidc_postman" {
  environment_id = pingone_environment.dev.id
  application_id = pingone_application.postman.id
  resource_id    = data.pingone_resource.openid.id
  scopes = [
    "${data.pingone_resource_scope.openid_openid.id}",
    "${data.pingone_resource_scope.openid_profile.id}",
    "${data.pingone_resource_scope.openid_email.id}",
    "${data.pingone_resource_scope.openid_phone.id}"
  ]
}
```
NB: I have omitted the custom resources/grants

### Expected Behavior
access_token to be assigned the requested claims

### Actual Behavior
no OIDC claims are present in the access_token, and the Console UI shows the checkboxes unchecked even though the API claims to have the relevant IDs connected.

Attempting to manually connect the scope by ticking the box in the UI results in
API error
```json
{
  "id" : "71931063-bb96-44d2-829f-e5348fc05e80",
  "code" : "INVALID_DATA",
  "message" : "The data provided was invalid.",
  "details" : [ {
    "code" : "INVALID_VALUE",
    "target" : "resource",
    "message" : "grant to given resource already exists",
    "innerError" : {
      "existingId" : "1626d95a-6dd5-40a1-aee9-e9526d7e5110",
      "appId" : "d28a3a7a-cdfa-48d2-94d2-da0677cf1750",
      "resId" : "ce23b15e-4714-4ada-817f-901a4627399c"
    }
  } ]
}
```

### Steps to Reproduce
Load the HCL in to a Ping Environment and apply
Open Ping Console and check application has access to the OIDC resources 

![Screenshot 2023-06-02 at 4 40 56 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/38b134ff-b228-47b0-b626-dcb6415f2435)
![Screenshot 2023-06-02 at 4 42 59 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/50dcb6be-df97-4331-83d2-d2f2be3062c8)
![Screenshot 2023-06-02 at 4 55 44 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/783f3631-f32e-46dd-b1db-c17718392cab)

**Comment by patrickcping** [comment]
Hey @dbryar thanks for raising!  I'll look into this today

**Comment by patrickcping** [comment]
Hey @dbryar I've replicated the problem, it's resolved by changing the mappings in the `pingone_application_resource_grant`, by removing the `openid` scope mapping:
```
resource "pingone_application_resource_grant" "oidc_postman" {
  environment_id = pingone_environment.my_environment.id
  application_id = pingone_application.postman.id
  resource_id    = data.pingone_resource.openid.id
  scopes = [
    "${data.pingone_resource_scope.openid_address.id}",
    "${data.pingone_resource_scope.openid_profile.id}",
    "${data.pingone_resource_scope.openid_email_test.id}",
    "${data.pingone_resource_scope.openid_phone.id}"
  ]
}
```

That example also includes adding the `address` scope mapping as it might be the intention here.

I've labelled this issue as an enhancement, to validate (before the API POST) that the `openid` scope isn't added to the `scopes` set of `pingone_application_resource_grant`

**Comment by dbryar** [comment]
Many thanks.

I'll confirm next deploy (Monday)
