### ISSUE TITLE
Permission assignments on a user to not throw an error

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Assigning duplicate roles during `apply` throws a hard error. It would be better if the duplicate permission being granted instead only generated a warning or non blocking error. Importing users and all their existing permissions when a new admin user is included in the admins list is difficult due to the import requiring the role "relationship" `id`, not just the user `id` and role `id`

### New or Affected Resource(s)

- pingone_role_assignment_user

Maybe allow a field to ignore duplicate?

### Potential Terraform Configuration

```hcl
resource "pingone_role_assignment_user" "terraform_sso_identity_admin" {
  environment_id       = pingone_environment.admin.id
  user_id              = data.pingone_user.terraform.id
  role_id              = data.pingone_role.identity_data_admin.id
  scope_environment_id = pingone_environment.dev.id
}

resource "pingone_role_assignment_user" "terraform_sso_environment_admin" {
  environment_id       = pingone_environment.admin.id
  user_id              = data.pingone_user.terraform.id
  role_id              = data.pingone_role.environment_admin.id
  scope_environment_id = pingone_environment.dev.id
}
```

### Current Behaviour
A duplicate role assignment will cause a hard stop during `apply`

### Desired Behaviour
A Duplicate role assignment displays a message such as "User `terraform` already has the `environment_admin` role with the scope `pingone_environment.dev.id` assigned"

**Comment by patrickcping** [comment]
hey @dbryar generating a non-blocking warning makes sense to me, I'll just need to consider if there are any drift-based side effects of that implementation

**Comment by dbryar** [comment]
Thanks, it would probably be a good idea to extend the same logic to application grants.
If a `scope` has been added to an application manually, then the same error occurs during `apply` for the application
```
│ Error: Error when calling `CreateApplicationGrant`: The data provided was invalid.
│ 
│   with pingone_application_resource_grant.test_app,
│   on dev.tf line 1519, in resource "pingone_application_resource_grant" "test_app":
│ 1519: resource "pingone_application_resource_grant" "test_app" {
│ 
│ PingOne Error Details:
│ ID: 53defd69-ca2a-4476-aa80-282b6f5eb602
│ Code: INVALID_DATA
│ Message: The data provided was invalid.
│ Details object: [{"code":"INVALID_VALUE","innerError":{},"message":"grant
│ to given resource already exists","target":"resource"}]
```

**Comment by patrickcping** [comment]
@dbryar Pulling together the list of resources that should have this behaviour, does this list look reasonable?  Are there any missing that you think should be on the list?

- `pingone_gateway_role_assignment`
- `pingone_role_assignment_user`
- `pingone_application_flow_policy_assignment`
- `pingone_application_resource_grant`
- `pingone_application_role_assignment`
- `pingone_application_sign_on_policy_assignment`

**Comment by dbryar** [comment]
I don't know if that is exhaustive as we are only using a portion of the feature set, but I have no further items to add.

**Comment by patrickcping** [comment]
@dbryar just to check the expectation here, using the `pingone_application_resource_grant` as the example case, if we ignore the resource grant and issue a warning we still wouldn't absorb that specific resource grant definition into Terraform state.  This means that the plan will _always_ show an intention to add the `pingone_application_resource_grant` role, unless it is removed from the HCL.

Essentially, a warning might help with initial development, but it still requires intervention on the HCL to avoid unnecessary apply runs.  I feel it might be correct behaviour to error/hard stop on conflict, as it is showing that those elements of configuration are being unexpectedly owned outside of Terraform and would need bringing into the HCL.

Would it fit your use case better if instead data sources were created that allowed you to create conditional statements on these resources? For example, to plan & apply a resource grant only if it doesn't already exist?

With these data sources, you'd also be able to implement [Terraform checks](https://developer.hashicorp.com/terraform/tutorials/configuration-language/checks)

**Comment by dbryar** [comment]
One of the issues that is triggering the actual failure is the overlap in role assignments.

If a user is assigned the `ORGANIZATION` scoped `Environment Admin` they cannot also be assigned the `ENVIRONMENT` scope to `Environment Admin`. The original request was to ignore the `Error` and instead `Warn` is the problem should be non-blocking.

```
╷
│ Error: Error when calling `CreateUserRoleAssignment`: The request could not be completed. One or more validation errors were in the request.
│ 
│   with pingone_role_assignment_user.first_last_example_com_au_environment_admin,
│   on dev.tf line 76, in resource "pingone_role_assignment_user" "first_last_example_com_au_environment_admin":
│   76: resource "pingone_role_assignment_user" "first_last_example_com_au_environment_admin"{
│ 
│ PingOne Error Details:
│ ID: f21b1537-3a54-45e8-9c02-638c0b54a7d0
│ Code: INVALID_DATA
│ Message: The request could not be completed. One or more validation errors
│ were in the request.
│ Details object: [{"code":"UNIQUENESS_VIOLATION","message":"May not assign
│ duplicate Role","target":"role"}]
╵
```

I attempted to circumvent the unwanted behaviour by forcing an import of all user roles mentioned in the HCL but this particular error is not avoidable due to the "AND" logic being applied in HCL, and the "OR" logic in Ping One

```
let role = A, scope = 2;

// HCL checks the following against state
if(role == A && scope == 2) then ...

// Ping One API verifies against assignments as such
if(role == A && scope > 1`
```
When `scope = 3` Terraform tries to apply but Ping One rejects

**Comment by dbryar** [comment]
While the proposed use of checks is probably going to work for the other items, the user roles issue will still persist

**Comment by patrickcping** [comment]
The making the role assignment non-blocking would still have the same plan problem:

1. Add `pingone_role_assignment_user` to the HCL
2. `terraform plan`: The plan wants to add the `pingone_role_assignment_user` resource
3. `terraform apply`: An error is returned showing a duplicate.  To make a warning will be non-blocking (as requested)
4. `terraform plan`: The plan wants to add the `pingone_role_assignment_user` resource
5. etc...
6. Remove `pingone_role_assignment_user` from the HCL
7. `terraform plan`: Plan completes without change, only when the resource is removed

This approach might work for a one-off 'data seeding' scenario, but it wouldn't be effective if there are role differences for users between dev-test-prod and you carry the same HCL between each.

My proposal would instead lead to something like this:
```terraform
data "pingone_environment" "admins_environment" {
    # ...
}

resource "pingone_environment" "my_environment" {
    # ...
}

data "pingone_role" "environment_admin" {
  name = "Environment Admin"
}

// NEW DATASOURCE START
data "pingone_role_assignments_user" "user_role_assignments" {
    environment_id = data.pingone_environment.admins_environment.id // the environment the admin user belongs to

    user_id = var.user_id
}
// NEW DATASOURCE END

resource "pingone_role_assignment_user" "environment_admin_to_user" {

  // only create the role assignment if the role assignment isn't already scoped at the organization level
  count = length(
    [
        for role_assignment in data.pingone_role_assignments_user.user_role_assignments.role_assignments : role_assignment.id
            if 
                role_assignment.role_id == data.pingone_role.environment_admin && // the role is the environment admin role
                role_assignment.scope_organization_id == var.organizaton_id // the role is scoped to the organization
    ]
  ) == 0 ? 1 : 0

  environment_id = data.pingone_environment.admins_environment.id // the environment the admin user belongs to
  user_id        = var.user_id
  role_id        = data.pingone_role.environment_admin.id // environment admin role

  scope_environment_id = pingone_environment.my_environment.id // the new environment
}
```

**Comment by patrickcping** [comment]
@dbryar `v0.18.0` was released today which allows for the solution documented in #478 - when you have the time to test, it will be good to know if this solves the problem or if further work might be needed

**Comment by dbryar** [comment]
I have integrated the changes in to the `plan` and I'm testing on a `dev` env to check assignments at the end of `apply`

My concern is the change to the state given

```
# pingone_role_assignment_user.environment_admin_assignment[MASKED] will be created
  + resource "pingone_role_assignment_user" "environment_admin_assignment" {
      + environment_id       = "[MASKED]"
      + id                   = (known after apply)
      + read_only            = (known after apply)
      + role_id              = "29ddce68-cd7f-4b2a-b6fc-f7a19553b496"
      + scope_environment_id = [MASKED]
      + user_id              = [MASKED]
    }
  # pingone_role_assignment_user.[MASKED]_environment_admin will be destroyed
  # (because pingone_role_assignment_user.[MASKED]_environment_admin is not in configuration)
  - resource "pingone_role_assignment_user" "[MASKED]_environment_admin" {
      - environment_id       = [MASKED] -> null
      - id                   = "9b5a34bc-01cb-439c-a4dc-b35aea1989e7" -> null
      - read_only            = false -> null
      - role_id              = "29ddce68-cd7f-4b2a-b6fc-f7a19553b496" -> null
      - scope_environment_id = [MASKED] -> null
      - user_id              = [MASKED] -> null
    }
```

so hopefully, no one loses access

**Comment by dbryar** [comment]
The first `apply` after the change removed the permissions from everyone 😢 

The `for_each` new method ran in to the same error as before
```
│ Error: Error when calling `CreateUserRoleAssignment`: The request could not be completed. One or more validation errors were in the request.
│ 
│   with pingone_role_assignment_user.environment_admin_assignment["d9ed3a1a-1589-43f8-8fe6-845101e7d9ce"],
│   on dev.tf line 108, in resource "pingone_role_assignment_user" "environment_admin_assignment":
│  108: resource "pingone_role_assignment_user" "environment_admin_assignment"{
│ 
│ PingOne Error Details:
│ ID: 35458203-2ec3-46b1-b017-d8ccda3674e0
│ Code: INVALID_DATA
│ Message: The request could not be completed. One or more validation errors
│ were in the request.
│ Details object: [{"code":"UNIQUENESS_VIOLATION","message":"May not assign
│ duplicate Role","target":"role"}]
```

**Comment by patrickcping** [comment]
Understood on the `terraform state mv`.

The first apply _would_ remove permissions as per the `plan` phase.  What I believe would happen on the first apply is that the roles on the new method would attempt to be _created at the same time_ as the removal of the roles on the previous method, leading to that error you see.  It would be the same if you migrated the role assignment into your own module, for example, and would also apply if moving an MFA device policy with a duplicate name, for example. 

You should see successful role assignment (without error) on a second/repeat `apply`, now the previous role assignments have been removed cleared from conflict.  Is that what happened in this case?

**Comment by patrickcping** [comment]
Ok thanks for confirming.  I'll leave this issue open for a while to collect additional feedback from yourself or others in the community, in case there is further work needed

**Comment by patrickcping** [comment]
Since last reviewing this issue, a couple of things have changed that mean that role conflicts can be avoided.

1. Roles can now be assigned to groups of users.  It's now best practice to assign roles to groups, and users to those groups, as user-level role conflicts are implicitly resolved.  See [Best Practices Documentation](https://terraform.pingidentity.com/best-practices/pingone/#use-group-role-assignments-over-terraform-managed-user-role-assignments)
2. A new guide has been created detailing admin role considerations.  See [Admin Role Management Considerations](https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/guides/admin-role-management)

There isn't anything more we can do in the provider until custom roles are available in the platform, so closing this issue.
