### ISSUE TITLE
Add `email_phone_verification` as a supported `template_name` in `pingone_notification_template_content`

### ISSUE THREAD

**Issue by mjspi** [pingidentity/terraform-provider-pingone#416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

version 1.5

### Affected Resource(s)

- pingone_notification_template_content

### Terraform Configuration Files
```hcl
resource "pingone_notification_template_content" "%[3]s" {
    environment_id = pingone_environment.%[2]s.id
    template_name  = "email_phone_verification"
    locale         = "en"

    sms {
        content = "Please approve this transaction with passcode $${otp}."
        sender  = "BX Retail"
    }

    variant = "sampleABC"
}
```

### Debug Output

```
        Error: expected template_name to be one of [email_verification_admin email_verification_user general transaction verification_code_template recovery_code_template device_pairing strong_authentication], got email_phone_verification
        
          with pingone_notification_template_content.oxbciundov,
          on terraform_plugin_test.tf line 28, in resource "pingone_notification_template_content" "oxbciundov":
          28:     template_name  = "email_phone_verification"
```
### Panic Output

N/A
### Expected Behavior

PingOne Verify notification templates are named `email_phone_verification`. The `template_name` should be allowed.

### Actual Behavior

The provider prevents usage of a template_name of `email_phone_verification`.  

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Issue is singularly focused on the P1Verify notification template, however there are additional templates for P1Credentials that may also be considered (likely in a separate enhancement request)
- credential_issued
- credential_updated
- credential_revoked
- digital_wallet_pairing
### References

- PR403 introduced an update to validate the variant_name provided in the P1Verify policy exists in P1. Testing identified that it was not possible to create a P1Verify notification template variant because `email_phone_verification` is not allowed as a value in the resource type `pingone_notification_template_content`.

**Comment by mjspi** [comment]
Testing has revealed additional triage is required. The P1Verify template behavior unexpectedly returning `Error: Content must contain all required variables.` error in the provider when using the same content as a postman call that is successful.

**Comment by patrickcping** [comment]
> Testing has revealed additional triage is required. The P1Verify template behavior unexpectedly returning `Error: Content must contain all required variables.` error in the provider when using the same content as a postman call that is successful.

@mjspi This will need a new issue creating, each template type needs proper plan validation which we add after this resource migrates to the plugin framework SDK

**Comment by mjspi** [comment]
100% agree.  I actually started down that path yesterday, but it started to morph into a larger effort that would've delayed getting this quick enhancement out there.  I'll get a new issue to track test case expansion for each individual notification template.
