### ISSUE TITLE
Schema Attributes with optional regex or enum fails validation

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version

0.16.0

### Terraform Version

1.4.2

### Affected Resource(s)

- pingone_schema_attribute

### Terraform Configuration Files
```hcl
resource "pingone_schema_attribute" "profile" {
  environment_id = pingone_environment.dev.id
  schema_id      = data.pingone_schema.user.id
  name           = "profile"
  display_name   = "Profile ID"
  description    = "Profile ID in the user database"
  type           = "STRING"
  unique         = false
  enabled        = true
  multivalued    = false
  regex_validation {
    pattern                         = "/test/"
    requirements                    = "string"
    values_pattern_should_match     = "test"
    values_pattern_should_not_match = "1234"
  }
}
```

### Debug Output
```
Error: Unsupported argument
   on dev.tf line 220, in resource "pingone_schema_attribute" "profile":
  220:   regex_validation = {
 
An argument named "regex_validation" is not expected here.
```

### Expected Behavior
Should be accepted per documentation

### Actual Behavior
Fails `terraform validate`

### Steps to Reproduce

1. add a custom schema attribute with a `regex_validation` or `enumerated_values` key
2. `terraform validate`

**Comment by patrickcping** [comment]
hey @dbryar , thanks for raising!  I agree, this isn't clear in the documentation, I'll add an example for the next release.  For now though, this should work:

```hcl
resource "pingone_schema_attribute" "profile" {
  environment_id = pingone_environment.my_environment.id
  schema_id      = data.pingone_schema.users.id
  name           = "profile"
  display_name   = "Profile ID"
  description    = "Profile ID in the user database"
  type           = "STRING"
  unique         = false
  enabled        = true
  multivalued    = false
  regex_validation = {
    pattern      = "^[a-zA-Z0-9]*$",
    requirements = "Lowercase, uppercase and numeric."

    values_pattern_should_match = [
      "test123",
      "test456"
    ]

    values_pattern_should_not_match = [
      "test123!",
      "test456!"
    ]
  }
}
```

**Comment by dbryar** [comment]
Sadly @patrickcping I already tried that. 

This is a direct cut and paste of your example in to the HCL, with before and after results.

![Screenshot 2023-06-28 at 5 35 51 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/301b24c1-5bd5-41e2-9a11-31d6590111f9)
![Screenshot 2023-06-28 at 5 36 27 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/7cb7fe27-3151-4570-862b-c3b139002e44)

**Comment by patrickcping** [comment]
@dbryar From the same directory as your `plan`, can you please run `terraform version` and paste the output?  We should see something like:
```
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/pingidentity/davinci v0.1.9
+ provider registry.terraform.io/pingidentity/pingone v0.16.0
```

The important pieces will be the architecture (so I can check that specific binary build) and the pingone provider version should be `v0.16.0`

**Comment by dbryar** [comment]
🌴 🤕 

```
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/pingidentity/davinci v0.1.9
+ provider registry.terraform.io/pingidentity/pingone v0.15.1
```

Code version and workspace version...

**Comment by dbryar** [comment]
`terraform init -upgrade` and works now.
