### ISSUE TITLE
Changing a client application from sign on policy to flow policy does not delete the old sign on policy

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#494]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version

0.18.1

### Terraform Version

1.4.2

### Affected Resource(s)

- pingone_application_flow_policy_assignment
- pingone_application_sign_on_policy_assignment

### Terraform Configuration Files
Changing from:
```hcl
resource "pingone_application_sign_on_policy_assignment" "app_sign_on_policy_1" {
  environment_id = pingone_environment.dev.id
  application_id = pingone_application.app.id
  sign_on_policy_id = pingone_sign_on_policy.da_vinci.id
  priority       = 1
}
```

to:
```hcl
resource "pingone_application_flow_policy_assignment" "app_flow_policy_1" {
  environment_id = pingone_environment.dev.id
  application_id = pingone_application.app.id
  flow_policy_id = davinci_application.ping_one_sso_connection.policy.* [index(davinci_application.ping_one_sso_connection.policy[*].name, "Customer Sign In")].policy_id
  priority       = 1
}
```

### Debug Output

```
# pingone_application_flow_policy_assignment.app_flow_policy_1 will be created
+ resource "pingone_application_flow_policy_assignment" "app_flow_policy_1" {
    + application_id = "0bca2fxxxxxxxx508"
    + environment_id = "02b158xxxxxxxx280"
    + flow_policy_id = (known after apply)
    + id             = (known after apply)
    + priority       = 1
  }
```

### Expected Behavior

Should be destroying the `sign_on_policy`

### Actual Behavior

App now has both a `flow_policy` and a `sign_on_policy` which is not allowed. The console disabled both and requests that one or the other type be disabled

### Steps to Reproduce

1. Create and app with a sign on policy
2. `terraform apply`
3. change to a flow policy
4. `terraform apply`

**Comment by dbryar** [comment]
![Screenshot 2023-07-25 at 9 54 40 pm](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/2ab1923a-d623-4dc3-9d48-31624d3e795a)

**Comment by patrickcping** [comment]
@dbryar thanks for raising!  I've not been able to replicate on my end though.

Some things to check:

1. Is it intermittent or does it happen each time?
2. Do you have a more complete example/cut-down anonymised HCL that you can share, that reliably shows the issue?
3. Are there more than one sign-on policies assigned to that application in the HCL?
4. If you run `terraform state show pingone_application_sign_on_policy_assignment.app_sign_on_policy_1` do you still see the sign-on policy assignment that should have been destroyed?
5. If you run plan and apply with debug on, do you see errors/warnings in the logs? e.g.
`TF_LOG=DEBUG TF_LOG_PATH=/path/to/output-plan.log terraform plan -out infra.tfout` and
`TF_LOG=DEBUG TF_LOG_PATH=/path/to/output-apply.log terraform apply "infra.tfout"`
6. It might be worth upgrading Terraform CLI to version `1.5.*`, in case you're hitting a Terraform specific bug.  If the resource to destroy is missing from the plan, this will be something to do with the internals of Terraform in how it builds the resource graph.

**Comment by dbryar** [comment]
I tested on a different application and it looks like it is working as expected.

The first application must not have had the `sign_on_policy_assignment` synced in the state? 
I will run `apply` from the `plan` output below to confirm.

```
  # pingone_application_flow_policy_assignment.app2_flow_policy_1 will be created
  + resource "pingone_application_flow_policy_assignment" "app2_flow_policy_1" {
      + application_id = "c7f917xxxdf27"
      + environment_id = "b7f122xxx5371"
      + flow_policy_id = "ffabffxxx3443"
      + id             = (known after apply)
      + priority       = 1
    }
  # pingone_application_sign_on_policy_assignment.app2_sign_on_policy_1 will be destroyed
  # (because pingone_application_sign_on_policy_assignment.app2_sign_on_policy_1 is not in configuration)
  - resource "pingone_application_sign_on_policy_assignment" "app2_sign_on_policy_1" {
      - application_id    = "c7f917xxxdf27" -> null
      - environment_id    = "b7f122xxx5371" -> null
      - id                = "828d1bxxxed14" -> null
      - priority          = 1 -> null
      - sign_on_policy_id = "774eb1xxx8eae" -> null
    }
```

**Comment by dbryar** [comment]
![Screenshot 2023-07-26 at 9 50 47 am](https://github.com/pingidentity/terraform-provider-pingone/assets/20749904/48805a53-5a80-4dbe-8a51-82e8707030a0)

Works, except for some reason the DaVinci policy is not showing properly

NB: The error in this screenshot has a typo in `disabled` where it is missing the `s`

**Comment by dbryar** [comment]
Update to the above; the `trigger` was missing from the deploy on the policy, so it was not available as a ping one flow policy. Fixed now.

**Comment by dbryar** [comment]
Safe to close
