### ISSUE TITLE
Add DaVinci admin roles to documentation example and validate provider compatibility

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-pingone#495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- `pingone_role`

### Potential Terraform Configuration

```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
```

### References

* #0000

**Comment by dbryar** [comment]
The new DaVinci roles are not available in the `plan`. 
I've left a full breakdown in #496

**Comment by patrickcping** [comment]
So watchers of this issue are aware, the general support of the DaVinci admin roles needs to be pushed into a later release.  This is because the roles cannot be re-granted from the worker app client that Terraform uses in the `provider {}` block.

The existing combinations of `Environment Admin` and `Identity Data Admin` will continue to work in the interim

Currently support for DaVinci admin roles is aligned to the `v0.20.0` release of the provider, but this can change.  If we have the ability to pull the release of the DaVinci admin roles forward then we will

**Comment by patrickcping** [comment]
The required changes to the API were made at the end of last week so we're able to include DaVinci role support in the `v0.19.0` release
