### ISSUE TITLE
Unable to assign users to groups

### ISSUE THREAD

**Issue by icsrmontano** [pingidentity/terraform-provider-pingone#523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, the only way to assign users to groups is via SCIM filter. The request is to allow direct assign users to groups.

Example:

resource "pingone_group_assignment_user" "test" {
  environment_id = pingone_environment.my_environment.id
  group_id = pingone_group.test.id
  users = [
    pingone_user.test1.id,
    pingone_user.test2.id,
  ]
}

### New or Affected Resource(s)

pingone_group_assignment_user

### Potential Terraform Configuration

```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
```

### References

* https://apidocs.pingidentity.com/pingone/platform/v1/api/#post-add-user-to-group

**Comment by patrickcping** [comment]
The implementation of this resource should follow the API described here: https://apidocs.pingidentity.com/pingone/platform/v1/api/#post-add-user-to-group

This means the resource will be `pingone_user_group_assignment` and will have syntax similar to:

```hcl
resource "pingone_user_group_assignment" "foo" {
  environment_id = pingone_environment.my_environment.id
  user_id = pingone_user.bar.id
  group_id = pingone_group.foobar.id
}
```
