### ISSUE TITLE
Unable to disable Self-Service system application

### ISSUE THREAD

**Issue by kwevers** [pingidentity/terraform-provider-pingone#527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PingOne Terraform provider Version
0.19.1

### Terraform Version
v1.5.5

### Affected Resource(s)
- pingone_system_application

### Terraform Configuration Files
```hcl
resource "pingone_system_application" "self_service" {
  enabled        = false
  environment_id = pingone_environment.this.id
  type           = "PING_ONE_SELF_SERVICE"
}
```

### Debug Output
```
Planning failed. Terraform encountered an error while generating this plan.

│ 
│ Error: Invalid Attribute Combination
│ 
│   with module.prd.pingone_system_application.self_service,
│   on ../../tf-mod-p1-env/main.tf line 246, in resource "pingone_system_application" "self_service":
│  246:   enabled        = false
│ 
│ Ensure that the boolean is set to true when the value "PING_ONE_SELF_SERVICE" is present in the following path expression: type
│ 
```

### Expected Behavior
This config should disable the `PingOne Self-Service - MyAccount` app. This is possible through the GUI, so there doesn't appear to be a reason not to support / allow this in the Terraform resource.

### Actual Behavior
The plan fails, see debug output section.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Disabling the application portal (`type = "PING_ONE_PORTAL"`) does work.
The provider documentation also doesn't mention this limitation.

**Comment by patrickcping** [comment]
Hi @kwevers thanks for raising!  This is intentional:

> This is possible through the GUI, so there doesn't appear to be a reason not to support / allow this in the Terraform resource.

For the most part, it isn't possible to disable the self-service app in the GUI, as the toggle button is purposefully disabled.  I'll look to see if there are specific edge-cases that do enable the toggle button, but while I check please can you verify that the toggle in the GUI for the self service app is enabled and you can actually disable the self-service app?

**Comment by patrickcping** [comment]
Ok thanks - let me know though if you see your environment gains the ability to disable the self-service app.

For the `Experiences/Self Service` menu:
#### Branding and Themes
- Apply Active Theme - *Not yet supported on the provider*
- Show Footer - *Not yet supported on the provider*

#### Self Service Section
This can be managed through the `pingone_application_resource_grant` resource ([link](https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/resources/application_resource_grant)), as they're all scopes from the `PingOne API` resource.  We do need to document this fully, but for now you might be able to configure what you need from:

- Manage Profile - `p1:update:user` and `p1:read:user` scopes
- Manage Authentication - `p1:create:pairingKey`, `p1:create:device`, `p1:delete:device`, `p1:read:device`, `p1:read:pairingKey`, `p1:update:device` scopes
- Enable or Disable MFA - `p1:update:userMfaEnabled` scope
- Change Password - `p1:read:userPassword`, `p1:reset:userPassword`, `p1:validate:userPassword` scopes
- Manage Linked Accounts - `p1:delete:userLinkedAccounts`, `p1:read:userLinkedAccounts` scopes
- Manage Sessions - `p1:delete:sessions`, `p1:read:sessions` scopes
- View Agreements - `p1:read:userConsent` scope
- Manage OAuth Consents - `p1:read:oauthConsent`, `p1:update:oauthConsent` scopes

**Comment by patrickcping** [comment]
#532 created to support the options under **Branding and Themes** on the `Experiences/Self Service` menu
