### ISSUE TITLE
Support for default / system applications

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-pingone#54]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for modification of the default or system applications, delivered when an environment is created:

- PingOne Admin Console
- PingOne Application Portal
- PingOne Self Service - MyAccount

The intention is to provide an 'override' interface to these applications, as they cannot be managed through pure CRUD.

### New or Affected Resource(s)

- pingone_system_application

**Comment by dbryar** [comment]
Add `PingOne DaVinci Connector` to the list

**Comment by dbryar** [comment]
This also applies to the `DaVinci Identity Provider`

**Comment by patrickcping** [comment]
Added #339 to track DV related default configuration

**Comment by patrickcping** [comment]
After review, the "PingOne Admin Console" cannot be modified.  The implementation in the associated PR therefore focuses on the ability to change configuration for (and assign policies/grants to):

- PingOne Application Portal
- PingOne Self Service - MyAccount
