### ISSUE TITLE
Support the ability to set the presented identity provider for authentication policy actions of type 'login'

### ISSUE THREAD

**Issue by sokolbpg** [pingidentity/terraform-provider-pingone#614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently the pingone_sign_on_policy_action resource does not support the ability to set the "Presented Identity Providers" when using the 'login' policy action.  This however, is supported via the UI.  The only option currently is to set a gateway.  Note: this is separate functionality from the 'identity_provider' policy action.  When using the 'identity_provider' policy action there is no longer an option for local login, but when using the 'login' policy action coupled with an identity provider you can still login locally, while having the option to login via an IdP.  An example of how this is setup in the UI is shown below:

![Presented Identity Providers Feature Request](https://github.com/pingidentity/terraform-provider-pingone/assets/62344165/9a652281-3f7c-4230-a729-eb53ece8cf3a)

### New or Affected Resource(s)

- pingone_sign_on_policy_action 

### Potential Terraform Configuration

```hcl
resource "pingone_sign_on_policy_action" "my_policy_first_factor" {
  environment_id    = pingone_environment.my_environment.id
  sign_on_policy_id = pingone_sign_on_policy.my_policy.id

  priority = 1
  enforce_lockout_for_identity_providers = true

  conditions {
    last_sign_on_older_than_seconds = 604800 // 7 days
  }

  login {
    recovery_enabled = true

    new_user_provisioning {
      identity_provider {
        identity_provider_id = pingone_identity_provider.my_identity_provider.id
        pass_user_context = true
      }
    }
  }
}
```

**Comment by patrickcping** [comment]
hi @sokolbpg thanks for raising!  For the configuration you need on the screenshot, you should be able to achieve the same with the `social_provider_ids` parameter.  For example:

```
resource "pingone_sign_on_policy_action" "my_policy_first_factor" {
  environment_id    = pingone_environment.my_environment.id
  sign_on_policy_id = pingone_sign_on_policy.my_policy.id

  priority = 1

  conditions {
    last_sign_on_older_than_seconds = 604800 // 7 days
  }

  login {
    recovery_enabled = true
  }

  social_provider_ids = [
    pingone_identity_provider.google.id
  ]
}
```

Let me know if this solves the problem.  If it does, I'll add it to the documentation example

**Comment by sokolbpg** [comment]
Hi @patrickcping using social_provider_ids works. Thanks for the quick response!
