### ISSUE TITLE
`409 Conflict` during `terraform destroy`

### ISSUE THREAD

**Issue by LubosMagda** [pingidentity/terraform-provider-pingone#632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PingOne Terraform provider Version
`0.22.0`

### Terraform Version
`1.6.3`

### Affected Resource(s)

- pingone_sign_on_policy
- pingone_mfa_policy

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    pingone = {
      source  = "pingidentity/pingone"
      version = ">= 0.22"
    }
  }
}

resource pingone_environment pingone_mfa_environment {
  name        = "Test Env"
  region      = "AsiaPacific"
  license_id  = "***"

  service {
    type = "MFA"
  }
}

resource pingone_sign_on_policy a_sign_on_policy {
  environment_id = pingone_environment.pingone_mfa_environment.id
  name           = "A_Sign_On_Policy"
}

resource pingone_mfa_policy a_mfa_policy {
  environment_id = pingone_environment.pingone_mfa_environment.id
  name           = "A MFA Device Policy"

  mobile { enabled = false }
  totp { enabled = false }
  email { enabled = false }
  sms { enabled = false }
  voice { enabled = false }
  fido2 { enabled = false }
}

resource pingone_sign_on_policy_action a_sign_on_policy_action {
  environment_id    = pingone_environment.pingone_mfa_environment.id
  sign_on_policy_id = pingone_sign_on_policy.a_sign_on_policy.id
  priority          = 1

  mfa {
    device_sign_on_policy_id = pingone_mfa_policy.a_mfa_policy.id
  }
}
```

### Debug Output
[terraform_apply.log](https://github.com/pingidentity/terraform-provider-pingone/files/13256404/terraform_apply.log)
[terraform_destroy_1.log](https://github.com/pingidentity/terraform-provider-pingone/files/13256405/terraform_destroy_1.log)
[terraform_destroy_2.log](https://github.com/pingidentity/terraform-provider-pingone/files/13256406/terraform_destroy_2.log)

### Expected Behavior
`terraform destroy` should successfully complete on the first execution and completely remove the environment.

### Actual Behavior
The first `terraform destroy` fails with a `Error: Error when calling `DeleteDeviceAuthenticationPolicy`: 409 Conflict` error. The second  `terraform destroy` succeeds.

Terraform seems to execute the deletion of the resources in an incorrect order (not taking into account the resource's dependencies).

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy` (fails with 409 Conflict)
3. `terraform destroy` (succeeds)

**Comment by patrickcping** [comment]
hi @LubosMagda thanks for raising!  In my testing Terraform appears to be removing resources in the correct order, but we have a bug in the provider brought on by the workaround for #68 
Essentially, the last `pingone_sign_on_policy_action` of a `pingone_sign_on_policy` cannot be removed (it's an API restriction), so we leave it in place.  But in doing so we leave that relationship to the `pingone_mfa_policy` which leads to the 409 conflict we see.
This will be fixed in the next version of the provider.

**Comment by LubosMagda** [comment]
Thank you! 👍 👍 👍

**Comment by LubosMagda** [comment]
It works well now!
