### ISSUE TITLE
Support CORS settings for application

### ISSUE THREAD

**Issue by alekamuniqa** [pingidentity/terraform-provider-pingone#671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There is a new feature that has been implemented in PingOne which our organisation has been requesting. It is related to CORS settings on Application level.
In the PingOne console, it is possible to set specific CORS settings per application as visible from this screenshot:
![image](https://github.com/pingidentity/terraform-provider-pingone/assets/135047369/6cf9d7ab-a1ec-420b-ab58-368795e5daf6)

These settings should be configurable via terraform, otherwise they would be overwritten with every new deployment via terraform. 
All features that are supported via the PingOne console for CORS should be supported via terraform (also wildcards for example).

### New or Affected Resource(s)

- pingone_application (introduce a new nested schema named for example "cors" which would contain everything needed?)

### Potential Terraform Configuration

```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
```

### References

* #0000

**Comment by patrickcping** [comment]
For those watching this issue and waiting for this feature, I've released `v0.24.0` today that includes these CORS settings.  [OIDC app doc link](https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/resources/application#nested-schema-for-oidc_optionscors_settings) / [SAML app doc link](https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/resources/application#nested-schema-for-saml_optionscors_settings)
