### ISSUE TITLE
password_length.min can only be set to 8

### ISSUE THREAD

**Issue by icsrmontano** [pingidentity/terraform-provider-pingone#738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
[1.7.4]

### Affected Resource(s)
- pingone_password_policy

### Terraform Configuration Files
  {
    "resource": {
      "pingone_password_policy": {
        "contoso_users": {
          "environment_id": "${pingone_environment.my_environment.id}",
          "name": "contoso_users_Population",
          "description": "Password policy for contoso_users_Population",
          "exclude_commonly_used_passwords": false,
          "exclude_profile_data": false,
          "password_length": {
            "min": 12,
            "max": 255
          },
          "min_characters": {
            "alphabetical_uppercase": 1,
            "alphabetical_lowercase": 1,
            "numeric": 1,
            "special_characters": 1
          }
        }
      }
    }
  },

### Debug Output
+ terraform plan
╷
│ Error: expected min to be in the range (8 - 8), got 12
│ 
│   with pingone_password_policy.username_password_authentication,
│   on pingone.tf.json line 432, in [23].resource.pingone_password_policy.username_password_authentication.password_length:
│  432:             "min": 12,

### Expected Behavior
PingOne should accept other values such as 12

### Actual Behavior
only accepted value is 8

### Steps to Reproduce
terraform plan

### References

- GH-1234

**Comment by patrickcping** [comment]
hi @icsrmontano !  Thanks for raising.  When the resource was originally created, the min password length was fixed at 8.  I can see that this changed in March 2022, so we'll continue to view this as a defect.

It's a straightforward change, so will target a patch release for the next week or so.
