### ISSUE TITLE
pingone_gateway (ldap): Changing the "password authority" value of a user_type forces recreate

### ISSUE THREAD

**Issue by janrenard** [pingidentity/terraform-provider-pingone#753]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

We have an pingone_gateway instance configured via terraform. This is an LDAP gateway connected to an on prem AD.
We now want to move the password authority from LDAP to PING_ONE for a user_type. If we do this via the WEBUI , this works fine, but via terraform the user-type is recreated (new ID). This action affects the all users connected to this gateway (the user_type is present in the user configuration).

### PingOne Terraform provider Version
0.26

### Terraform Version
Terraform v1.5.7

### Affected Resource
- pingone_gateway

### Terraform Configuration Files
resource "pingone_gateway" "example" {
  environment_id            = pingone_environment.environment.id
  name                      = "AD_${terraform.workspace}"
  enabled                   = true
  type                      = "LDAP"
  vendor                    = "Microsoft Active Directory"
  connection_security       = "StartTLS"
  bind_dn                   = var.p1_gtw_bind_dn
  bind_password             = var.p1_gtw_bind_pwd
  servers                   = [ "1.1.1.1", "1.1.1.2"  ]
  user_type {
    name                          = "Usr-${terraform.workspace}-Customers"
    password_authority            = "LDAP"
    #password_authority            = "PING_ONE"
  }
}

### Expected Behavior
Terraform should update both the pingone_gateway and the user_type in-place

### Actual Behavior
Terraform removes the existing user_type and recreates it.

Terraform will perform the following actions:

  # pingone_gateway.example[0] will be updated in-place
  # (moved from pingone_gateway.example)
  ~ resource "pingone_gateway" "example" {
      + bind_password                             = (sensitive value)
        id                                        = "e0e4e65a-0311-4504-a604-9f848cb889fd"
        name                                      = "AD_production"
        # (9 unchanged attributes hidden)

      - user_type {
          - id                            = "02ea68f9-2e6e-4e44-aed9-dc0f8b4c46ae" -> null
          - name                          = "Usr-production-Customers" -> null
          - password_authority            = "LDAP" -> null
          - push_password_changes_to_ldap = true -> null
          - search_base_dn                = "OU=example,DC=example,DC=com" -> null
          - user_link_attributes          = [
              - "middleName",
            ]
      + user_type {
          + id                            = (known after apply)
          + name                          = "Usr-production-Customers"
          + password_authority            = "PING_ONE"
          + push_password_changes_to_ldap = true
          + search_base_dn                = "OU=example,DC=example,DC=com"
          + user_link_attributes          = [
              + "middleName",
            ]

**Comment by janrenard** [comment]
Hi @patrickcping Thanks for your feedback. Will proceed as per your suggestion for now.

**Comment by patrickcping** [comment]
This will be resolved in the upcoming `v1.0` release.  The intention is to change the "set" data type to a "map", so the individual `user_type` embedded objects can be correctly correlated between the plan and the state.

Ref https://discuss.hashicorp.com/t/dealing-with-unordered-sets-of-complex-objects-setnestedattribute-with-computed-attributes/61874/1

**Comment by janrenard** [comment]
Hi Patrick,

Just back with another terraform related question.

It seems that the SAML assertion encryption for an application is currently not configurable with terraform (the signing by contrast is supported in terraform).

Is that on the horizon at the moment? It’s one of the last things holding us back to fully move to terraform.

If needed I can create a github feature request, but I was wondering if we were the first to ask?

BR,

Jan

From: Patrick Cowland ***@***.***>
Date: Thursday, 2 May 2024 at 11:21
To: pingidentity/terraform-provider-pingone ***@***.***>
Cc: Jan Renard ***@***.***>, Mention ***@***.***>
Subject: Re: [pingidentity/terraform-provider-pingone] pingone_gateway (ldap): Changing the "password authority" value of a user_type forces recreate (Issue #753)

This will be resolved in the upcoming v1.0 release. The intention is to change the "set" data type to a "map", so the individual user_type embedded objects can be correctly correlated between the plan and the state.

Ref https://discuss.hashicorp.com/t/dealing-with-unordered-sets-of-complex-objects-setnestedattribute-with-computed-attributes/61874/1

**Comment by janrenard** [comment]
Hi Patrick,

Indeed, it’s missing from the API documentation, the API does accept the encryption parameters. I already use the API to automate the SAML encryption settings.

This is (roughly) the template we use for the moment (part of the application json):

"spEncryption" : {

    "algorithm" : "{{ enc_type }}",

    "certificate" : {

      "id" : "{{ cert.id }}"

    }

  }

BR,

Jan

From: Patrick Cowland ***@***.***>
Date: Wednesday, 29 May 2024 at 11:33
To: pingidentity/terraform-provider-pingone ***@***.***>
Cc: Jan Renard ***@***.***>, Mention ***@***.***>
Subject: Re: [pingidentity/terraform-provider-pingone] pingone_gateway (ldap): Changing the "password authority" value of a user_type forces recreate (Issue #753)

Hey @janrenard<https://github.com/janrenard> , you're right it needs building into the provider. I don't see reference to it in the API documentation so I've raised the request internally to have that reviewed

In the meantime I've created the feature request at #823<https://github.com/pingidentity/terraform-provider-pingone/issues/823> . I'll look to include this in a minor release in the next week or so
