### ISSUE TITLE
Ldap gateway issue when vendor is LDAPv3-compliant Directory Server

### ISSUE THREAD

**Issue by jenniferstipe** [pingidentity/terraform-provider-pingone#867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version
v1.0.0-rc1
0.29.1

### Terraform Version
OpenTofu v1.7.2
on linux_amd64
+ provider registry.opentofu.org/pingidentity/pingone v1.0.0-rc1

### Affected Resource(s)
pingone_gateway

### Terraform Configuration Files
this hcl works for a plan, however it fails for an apply:
```hcl
resource "pingone_gateway" "vds_test_ldap_gateway" {
  environment_id = var.environment_id
  name           = "VDS Test LDAP Gateway"
  enabled        = true
  type           = "LDAP"

  bind_dn       = var.bind_dn
  bind_password = var.bind_password

  connection_security = "TLS"
  vendor              = "LDAP v3 compliant Directory Server"

  servers = [
    "fqdn.domain.com:636",
  ]

}
```
this hcl fails on a plan/apply:
```hcl
resource "pingone_gateway" "test_ldap_gateway" {
  environment_id = var.environment_id
  name           = "Test LDAP Gateway"
  enabled        = true
  type           = "LDAP"

  bind_dn       = var.bind_dn
  bind_password = var.bind_password

  connection_security = "TLS"
  vendor              = "LDAPv3-compliant Directory Server"

  servers = [
    "fqdn.domain.com:636",
  ]

}
```
Apply error:
2024-07-02T21:40:38.419-0400 [DEBUG] skipping FixUpBlockAttrs
2024-07-02T21:40:38.419-0400 [DEBUG] pingone_gateway.vds_test_ldap_gateway: applying the planned Create change   
2024-07-02T21:40:38.421-0400 [DEBUG] provider.terraform-provider-pingone_v1.0.0-rc1: 2024/07/02 21:40:38 [DEBUG] 
Waiting for state to become: [success]
2024-07-02T21:40:39.053-0400 [ERROR] provider.terraform-provider-pingone_v1.0.0-rc1: Response contains error diagnostic: tf_req_id=72071912-8027-715e-6b25-57e3379ebd02 tf_resource_type=pingone_gateway diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/pingidentity/pingone tf_rpc=ApplyResourceChange diagnostic_summary="Invalid Value" @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/diag/diagnostics.go:58 diagnostic_detail="must be one of [PingDirectory, Microsoft Active Directory, Oracle Directory Server Enterprise Edition, Oracle Unified Directory, CA Directory, OpenDJ Directory Server, IBM (Tivoli) Security Directory Server, LDAPv3-compliant Directory Server]" tf_proto_version=6.6 @module=sdk.proto timestamp=2024-07-02T21:40:39.053-0400   
2024-07-02T21:40:39.054-0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-07-02T21:40:39.054-0400 [ERROR] vertex "pingone_gateway.vds_test_ldap_gateway" error: Invalid Value
╷
│ Error: Invalid Value
│
│   with pingone_gateway.vds_test_ldap_gateway,
│   on gateway.tf line 2, in resource "pingone_gateway" "vds_test_ldap_gateway":
│    2: resource "pingone_gateway" "vds_test_ldap_gateway" {
│
│ must be one of [PingDirectory, Microsoft Active Directory, Oracle Directory Server Enterprise Edition, Oracle  
│ Unified Directory, CA Directory, OpenDJ Directory Server, IBM (Tivoli) Security Directory Server,
│ LDAPv3-compliant Directory Server]
╵
2024-07-02T21:40:39.061-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-07-02T21:40:39.066-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/pingidentity/pingone/1.0.0-rc1/linux_amd64/terraform-provider-pingone_v1.0.0-rc1 pid=202504
2024-07-02T21:40:39.067-0400 [DEBUG] provider: plugin exited

Plan error:
### Debug Output
2024-07-02T21:31:38.541-0400 [DEBUG] provider: using plugin: version=6
2024-07-02T21:31:38.541-0400 [DEBUG] provider.terraform-provider-pingone_v1.0.0-rc1: plugin address: address=/tmp/plugin832640753 network=unix timestamp=2024-07-02T21:31:38.541-0400
2024-07-02T21:31:38.617-0400 [DEBUG] skipping FixUpBlockAttrs
2024-07-02T21:31:38.653-0400 [ERROR] provider.terraform-provider-pingone_v1.0.0-rc1: Response contains error diagnostic: tf_provider_addr=registry.terraform.io/pingidentity/pingone tf_req_id=52747e72-6378-afc7-1d20-d5fb4930a11f tf_rpc=ValidateResourceConfig diagnostic_attribute="AttributeName(\"vendor\")" diagnostic_detail="Attribute vendor value must be one of: [\"PingDirectory\" \"Microsoft Active Directory\" \"Oracle Directory Server Enterprise 
Edition\" \"Oracle Unified Directory\" \"CA Directory\" \"OpenDJ Directory\" \"IBM (Tivoli) Security Directory Server\" \"LDAP v3 compliant Directory Server\"], got: \"LDAPv3-compliant Directory Server\"" diagnostic_summary="Invalid Attribute Value Match" @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=6.6 tf_resource_type=pingone_gateway @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/diag/diagnostics.go:58 timestamp=2024-07-02T21:31:38.653-0400
2024-07-02T21:31:38.653-0400 [ERROR] vertex "pingone_gateway.vds_test_ldap_gateway" error: Invalid Attribute Value Match
╷
│ Error: Invalid Attribute Value Match
│
│   with pingone_gateway.vds_test_ldap_gateway,
│   on gateway.tf line 12, in resource "pingone_gateway" "vds_test_ldap_gateway":
│   12:   vendor              = "LDAPv3-compliant Directory Server"
│
│ Attribute vendor value must be one of: ["PingDirectory" "Microsoft Active Directory" "Oracle Directory Server  
│ Enterprise Edition" "Oracle Unified Directory" "CA Directory" "OpenDJ Directory" "IBM (Tivoli) Security        
│ Directory Server" "LDAP v3 compliant Directory Server"], got: "LDAPv3-compliant Directory Server"
╵
2024-07-02T21:31:38.656-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-07-02T21:31:38.658-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/pingidentity/pingone/1.0.0-rc1/linux_amd64/terraform-provider-pingone_v1.0.0-rc1 pid=200065
2024-07-02T21:31:38.658-0400 [DEBUG] provider: plugin exited

### Expected Behavior
The ldap gateway should be applied correctly.

### Actual Behavior
Received the error above.

### Steps to Reproduce

1. `tofu plan -var-file=var_file.tfvars` with syntax a, successful plan
2. tofu apply -var-file=var_file.tfvars - Get error 
3. Change configuration to resolve error, tofu plan -var-file=var_file.tfvars
4. Fails to generate plan

### Important Factoids
It seems like there is a mismatch between what the plan syntax verification accepts (LDAP v3 compliant Directory Server) and what actually needs to be applied to PingOne (LDAPv3-compliant Directory Server).

**Comment by jenniferstipe** [comment]
> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.
> 
> ### PingOne Terraform provider Version
> v1.0.0-rc1 0.29.1
> 
> ### Terraform Version
> OpenTofu v1.7.2 on linux_amd64
> 
> * provider registry.opentofu.org/pingidentity/pingone v1.0.0-rc1
> 
> ### Affected Resource(s)
> pingone_gateway
> 
> ### Terraform Configuration Files
> this hcl works for a plan, however it fails for an apply:
> 
> ```hcl
> resource "pingone_gateway" "vds_test_ldap_gateway" {
>   environment_id = var.environment_id
>   name           = "VDS Test LDAP Gateway"
>   enabled        = true
>   type           = "LDAP"
> 
>   bind_dn       = var.bind_dn
>   bind_password = var.bind_password
> 
>   connection_security = "TLS"
>   vendor              = "LDAP v3 compliant Directory Server"
> 
>   servers = [
>     "marrvdstest.marriott.com:636",
>   ]
> 
> }
> ```
> 
> this hcl fails on a plan/apply:
> 
> ```hcl
> resource "pingone_gateway" "test_ldap_gateway" {
>   environment_id = var.environment_id
>   name           = "Test LDAP Gateway"
>   enabled        = true
>   type           = "LDAP"
> 
>   bind_dn       = var.bind_dn
>   bind_password = var.bind_password
> 
>   connection_security = "TLS"
>   vendor              = "LDAPv3-compliant Directory Server"
> 
>   servers = [
>     "fqdn.domain.com:636",
>   ]
> 
> }
> ```
> ### Debug Output 
> Apply error: 2024-07-02T21:40:38.419-0400 [DEBUG] skipping FixUpBlockAttrs 2024-07-02T21:40:38.419-0400 [DEBUG] pingone_gateway.vds_test_ldap_gateway: applying the planned Create change 2024-07-02T21:40:38.421-0400 [DEBUG] provider.terraform-provider-pingone_v1.0.0-rc1: 2024/07/02 21:40:38 [DEBUG] Waiting for state to become: [success] 2024-07-02T21:40:39.053-0400 [ERROR] provider.terraform-provider-pingone_v1.0.0-rc1: Response contains error diagnostic: tf_req_id=72071912-8027-715e-6b25-57e3379ebd02 tf_resource_type=pingone_gateway diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/pingidentity/pingone tf_rpc=ApplyResourceChange diagnostic_summary="Invalid Value" @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/diag/diagnostics.go:58 diagnostic_detail="must be one of [PingDirectory, Microsoft Active Directory, Oracle Directory Server Enterprise Edition, Oracle Unified Directory, CA Directory, OpenDJ Directory Server, IBM (Tivoli) Security Directory Server, LDAPv3-compliant Directory Server]" tf_proto_version=6.6 @module=sdk.proto timestamp=2024-07-02T21:40:39.053-0400 2024-07-02T21:40:39.054-0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot 2024-07-02T21:40:39.054-0400 [ERROR] vertex "pingone_gateway.vds_test_ldap_gateway" error: Invalid Value ╷ │ Error: Invalid Value │ │ with pingone_gateway.vds_test_ldap_gateway, │ on gateway.tf line 2, in resource "pingone_gateway" "vds_test_ldap_gateway": │ 2: resource "pingone_gateway" "vds_test_ldap_gateway" { │ │ must be one of [PingDirectory, Microsoft Active Directory, Oracle Directory Server Enterprise Edition, Oracle │ Unified Directory, CA Directory, OpenDJ Directory Server, IBM (Tivoli) Security Directory Server, │ LDAPv3-compliant Directory Server] ╵ 2024-07-02T21:40:39.061-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF" 2024-07-02T21:40:39.066-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/pingidentity/pingone/1.0.0-rc1/linux_amd64/terraform-provider-pingone_v1.0.0-rc1 pid=202504 2024-07-02T21:40:39.067-0400 [DEBUG] provider: plugin exited
> 
> Plan error:
> 
>
> 2024-07-02T21:31:38.541-0400 [DEBUG] provider: using plugin: version=6 2024-07-02T21:31:38.541-0400 [DEBUG] provider.terraform-provider-pingone_v1.0.0-rc1: plugin address: address=/tmp/plugin832640753 network=unix timestamp=2024-07-02T21:31:38.541-0400 2024-07-02T21:31:38.617-0400 [DEBUG] skipping FixUpBlockAttrs 2024-07-02T21:31:38.653-0400 [ERROR] provider.terraform-provider-pingone_v1.0.0-rc1: Response contains error diagnostic: tf_provider_addr=registry.terraform.io/pingidentity/pingone tf_req_id=52747e72-6378-afc7-1d20-d5fb4930a11f tf_rpc=ValidateResourceConfig diagnostic_attribute="AttributeName("vendor")" diagnostic_detail="Attribute vendor value must be one of: ["PingDirectory" "Microsoft Active Directory" "Oracle Directory Server Enterprise Edition" "Oracle Unified Directory" "CA Directory" "OpenDJ Directory" "IBM (Tivoli) Security Directory Server" "LDAP v3 compliant Directory Server"], got: "LDAPv3-compliant Directory Server"" diagnostic_summary="Invalid Attribute Value Match" @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=6.6 tf_resource_type=pingone_gateway @caller=github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/diag/diagnostics.go:58 timestamp=2024-07-02T21:31:38.653-0400 2024-07-02T21:31:38.653-0400 [ERROR] vertex "pingone_gateway.vds_test_ldap_gateway" error: Invalid Attribute Value Match ╷ │ Error: Invalid Attribute Value Match │ │ with pingone_gateway.vds_test_ldap_gateway, │ on gateway.tf line 12, in resource "pingone_gateway" "vds_test_ldap_gateway": │ 12: vendor = "LDAPv3-compliant Directory Server" │ │ Attribute vendor value must be one of: ["PingDirectory" "Microsoft Active Directory" "Oracle Directory Server │ Enterprise Edition" "Oracle Unified Directory" "CA Directory" "OpenDJ Directory" "IBM (Tivoli) Security │ Directory Server" "LDAP v3 compliant Directory Server"], got: "LDAPv3-compliant Directory Server" ╵ 2024-07-02T21:31:38.656-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF" 2024-07-02T21:31:38.658-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.opentofu.org/pingidentity/pingone/1.0.0-rc1/linux_amd64/terraform-provider-pingone_v1.0.0-rc1 pid=200065 2024-07-02T21:31:38.658-0400 [DEBUG] provider: plugin exited
> 
> ### Expected Behavior
> The ldap gateway should be applied correctly.
> 
> ### Actual Behavior
> Received the error above.
> 
> ### Steps to Reproduce
> 1. `tofu plan -var-file=var_file.tfvars` with syntax a, successful plan
> 2. tofu apply -var-file=var_file.tfvars - Get error
> 3. Change configuration to resolve error, tofu plan -var-file=var_file.tfvars
> 4. Fails to generate plan
> 
> ### Important Factoids
> It seems like there is a mismatch between what the plan syntax verification accepts (LDAP v3 compliant Directory Server) and what actually needs to be applied to PingOne (LDAPv3-compliant Directory Server).
> 
> ### References

**Comment by patrickcping** [comment]
Hi @jenniferstipe thanks for raising!  I agree with your conclusion, the provider needs correcting.  I'll line this up for the upcoming `v1.0.0-rc2` release

If you're using `v0.29` and currently blocked let me know and I'll look to issue a patch release for that version as well

**Comment by jenniferstipe** [comment]
> Hi @jenniferstipe thanks for raising! I agree with your conclusion, the provider needs correcting. I'll line this up for the upcoming `v1.0.0-rc2` release
> 
> If you're using `v0.29` and currently blocked let me know and I'll look to issue a patch release for that version as well

Hi @patrickcping thank you.  I could use a patch release for v0.29 unless the production ready release of v1.0.0-rc2 is going to be ready soon.  Thanks again, appreciate your help!

**Comment by patrickcping** [comment]
Sure - `v0.29.2` was released today ([doc link](https://registry.terraform.io/providers/pingidentity/pingone/0.29.2/docs/resources/gateway#vendor)) as `v1.0.0-rc2` isn't yet ready for production use when it gets released
